배포오류 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,10 +33,12 @@ jobs:
         run: npm ci
       - name: Build with Next.js
         run: npm run build
+      - name: Debug Output Directory
+        run: ls -la out || echo "Out directory not found!"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./out
+          path: "out"
 
   deploy:
     environment:
